# Generated by Django 4.2.10 on 2025-05-14 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_leaflet_leafletmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaflet',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.RemoveField(
            model_name='leafletmap',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='leafletmap',
            name='image',
        ),
        migrations.AddField(
            model_name='leafletmap',
            name='leaflet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leafletmaps', to='testapp.leaflet'),
        ),
        migrations.AddField(
            model_name='leafletmap',
            name='leafletmap',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaflet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Geometry name'),
        ),
    ]
