# Generated by Django 4.2.10 on 2025-05-14 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_leaflet_options_remove_leafletmap_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafletmap',
            name='leafletmap',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
