# Generated by Django 4.2.10 on 2025-05-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_leafletmap_leafletmap'),
    ]

    operations = [
    ]
