# Generated by Django 4.2.10 on 2025-06-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20250514_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafletmap',
            name='leaflet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leafletmaps', to='testapp.leaflet'),
        ),
    ]
