# Generated by Django 4.2.10 on 2025-06-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_leafletmap_leaflet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leafletmap',
            old_name='leafletmap',
            new_name='geometry',
        ),
    ]
