# Generated by Django 4.2.10 on 2025-06-02 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_rename_leafletmap_leafletmap_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafletmap',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
