# Generated by Django 4.2.10 on 2025-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_leafletmap_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafletmap',
            name='caption',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
