# Generated by Django 4.2.10 on 2025-12-09 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_leafletmap_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafletmap',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
