# Generated by Django 4.2.10 on 2025-12-10 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_leafletmap_geometry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaflet',
            new_name='Region',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.CreateModel(
            name='RegionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LeafletMap',
        ),
        migrations.AddField(
            model_name='regionmap',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionmaps', to='testapp.region'),
        ),
    ]
